{% set version = "0.1.2" %}

package:
  name: pep440
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pep440/pep440-{{ version }}.tar.gz
  sha256: 58b37246cc2b13fee1ca2a3c092cb3704d21ecf621a5bdbb168e44e697f6d04d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  source_files:
    - tests
  imports:
    - pep440
  commands:
    - pip check
    - pep440 --help
    - pytest tests --cov=pep440 --cov-branch --cov-report=term-missing:skip-covered --script-launch-mode=subprocess --cov-fail-under=100 --no-cov-on-fail
  requires:
    - pip
    - pytest
    - pytest-cov
    - pytest-console-scripts
    - python {{ python_min }}

about:
  home: https://github.com/Carreau/pep440
  summary: A simple package with utils to check whether versions number match PEP 440.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
